export enum LeaveType {
  CG_PAYE = "CG_PAYE",
  CG_SANS_SOLDE = "CG_SANS_SOLDE",
  CG_MALADIE = "CG_MALADIE",
  AUTORISATION = "AUTORISATION",
  EVENEMENT_FAMILIAL = "EVENEMENT_FAMILIAL",
  CG_PATERN = "CG_PATERN",
  CG_MATERN = "CG_MATERN",
  EVEN_FAM_DECES = "EVEN_FAM_DECES"
}
